services:
  db:
    image: postgres:17.0
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  api:
    build:
      dockerfile: Dockerfile
      args:
        - DB_URL=jdbc:postgresql://db:5432/inventory_db
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/inventory_db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}