spring:
  application:
    name: inventory-management
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop